version: "3.9"

services:
  db:
    image: postgres:15
    container_name: workout_db
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "1234:5432"   # mapeia a porta para o host
    volumes:
      - pgdata:/var/lib/postgresql/data  # mantém dados entre reinícios
    restart: unless-stopped

volumes:
  pgdata: